id: P009619
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:41:10.870076
source_metadata:
  id: bdr:W2PD17394
  title: 'པཎ་ཆེན་སྐུ་ཕྲེང་དང་པོ་ནས་སྐུ་ཕྲེང་བཞི་པའི་བར་གྱི་རྣམ་ཐར། '
  author: ''
  volumes:
    3caa9b77e14742ef877bf505a5c97afb:
      image_group_id: I4PD2975
      title: ''
      volume_number: 1
      total_pages: 450
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
